[data][twitter] Got empty sentence is split qa
- there are a lot empty lines, could be my fault when split
````
sockeye.utils.SockeyeError: Empty sentence in file
/home/at15/workspace/src/github.com/at15/snowbot-data/twitter/tgt-train.txt
````